# Generated by Django 2.1.11 on 2021-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_splitresult_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitresult',
            name='screenshot',
            field=models.FileField(upload_to='screenshot/'),
        ),
    ]
