# Generated by Django 2.1.11 on 2021-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20210407_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitresult',
            name='screenshot',
            field=models.TextField(null=True),
        ),
    ]
